# Generated by Django 2.2.5 on 2019-09-23 18:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boardgame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('summary', models.TextField(help_text='Enter a brief description of the board game', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(help_text='Enter a board game genre (e.g. Roll of the Die)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Playthrough',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this playthrough', primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('boardgame', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Boardgame')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Location')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.RemoveField(
            model_name='bookinstance',
            name='book',
        ),
        migrations.RemoveField(
            model_name='author',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='author',
            name='date_of_death',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='BookInstance',
        ),
        migrations.AddField(
            model_name='boardgame',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Author'),
        ),
        migrations.AddField(
            model_name='boardgame',
            name='genre',
            field=models.ManyToManyField(help_text='Select a genre for this board game', to='main.Genre'),
        ),
    ]
