# Generated by Django 2.2.5 on 2019-09-26 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190923_2157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='playthrough',
            options={'ordering': ['datetime']},
        ),
        migrations.RemoveField(
            model_name='playthrough',
            name='date',
        ),
        migrations.AddField(
            model_name='boardgame',
            name='bgg_overall_rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='boardgame',
            name='expected_playtime',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='boardgame',
            name='max_players',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='boardgame',
            name='min_players',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='boardgame',
            name='picture',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='playthrough',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playthrough',
            name='playtime',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='playthrough',
            name='players',
            field=models.ManyToManyField(help_text='Add players who participate in this game.', to='main.Player'),
        ),
    ]
