# Generated by Django 2.2.5 on 2019-10-01 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190926_2226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('bgg_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='boardgame',
            name='expected_playtime',
        ),
        migrations.RemoveField(
            model_name='boardgame',
            name='picture',
        ),
        migrations.AddField(
            model_name='boardgame',
            name='bgg_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='boardgame',
            name='image_url',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='boardgame',
            name='max_playtime',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='boardgame',
            name='min_playtime',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='boardgame',
            name='thumbnail_url',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='boardgame',
            name='year_published',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='genre',
            name='bgg_id',
            field=models.IntegerField(null=True),
        ),
    ]
