# Generated by Django 2.2.5 on 2019-10-29 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20191001_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='playthrough',
            name='rating',
            field=models.FloatField(null=True),
        ),
    ]
